export const LOAD_COMMENTS= "LOAD_COMMENTS"
export const ADD_COMMENT="ADD_COMMENT"
export const UPDATE_COMMENT="UPDATE_COMMENT"
export const DELETE_COMMENT="DELETE_COMMENT"

export const SET_CURRENT_USER="SET_CURRENT_USER"
export const SIGNUP_USER="SIGNUP_USER"
export const LOGOUT_USER="LOGOUT_USER"

export const FETCH_DRINKS="FETCH_DRINKS"
export const VIEW_DRINK="VIEW_DRINK"

export const SET_ERROR = "SET_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR"

