export const ADD_COMMENT="ADD_COMMENT"
export const REMOVE_COMMENT="REMOVE_COMMENT"
export const UPDATE_COMMENT="UPDATE_COMMENT"
export const DELETE_COMMENT="DELETE_COMMENT"

export const LOGIN_USER="LOGIN_USER"
export const SIGNUP_USER="SIGNUP_USER"
export const LOGOUT_USER="LOGOUT_USER"

export const FETCH_DRINKS="FETCH_DRINKS"
export const VIEW_DRINK="VIEW_DRINK"


